import type { MetadataRoute } from 'next';

// Web app manifest — makes the site installable and improves the mobile
// address-bar / splash experience. Next serves this at /manifest.webmanifest
// and auto-injects <link rel="manifest">. Icons are generated by
// scripts/make-og-image.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Kaizen Infotech Solutions',
    short_name: 'Kaizen Infotech',
    description:
      'Custom software, mobile apps, event management systems, enterprise web portals, and digital marketing solutions.',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    icons: [
      { src: '/images/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/images/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      {
        src: '/images/icons/icon-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
